#!/usr/bin/env bash
# Does a lot

echo $$ > /var/run/myscript.pid

sigterm_handler() {
    echo "I hate the kill command"
    cleanup
    exit 0
}
sigint_handler() {
    echo "Y U no love me?!"
}
sigquit_handler() {
    echo "Y U no love me?!"
    cleanup
    exit 0
}

trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT SIGTERM

cleanup() {
    rm /var/run/myscript.pid
}

while True
do
    echo "To infinity and beyond"
    sleep 2
done
